var reservationData = {
    
    "PartySizes": [
        {
            "PartySize": "2",
            "Tables":[
                {
                    "TableNumber":"1",
                    "ReservationTimes":[
                        {
                            "Time":"16",
                            "Reserved":true,
                            "User":""
                        },
                        {
                            "Time":"17",
                            "Reserved":false,
                            "User":""
                        },
                        {
                            "Time":"18",
                            "Reserved":true,
                            "User":""
                        },
                        {
                            "Time":"19",
                            "Reserved":true,
                            "User":""
                        },
                        {
                            "Time":"20",
                            "Reserved":false,
                            "User":""
                        }
                    ]
                },
                
                {
                    "TableNumber":"2",
                    "ReservationTimes":[
                        {
                            "Time":"16",
                            "Reserved":false,
                            "User":"replace"
                        },
                        {
                            "Time":"17",
                            "Reserved":false,
                            "User":""
                        },
                        {
                            "Time":"18",
                            "Reserved":true,
                            "User":""
                        },
                        {
                            "Time":"19",
                            "Reserved":true,
                            "User":""
                        },
                        {
                            "Time":"20",
                            "Reserved":false,
                            "User":""
                        }
                    ]
                }
            ]
        },
        
        {
            "PartySize": "4",
            "Tables":[
                {
                    "TableNumber":"3",
                    "ReservationTimes":[
                        {
                            "Time":"16",
                            "Reserved":false,
                            "User":""
                        },
                        {
                            "Time":"17",
                            "Reserved":false,
                            "User":""
                        },
                        {
                            "Time":"18",
                            "Reserved":true,
                            "User":""
                        },
                        {
                            "Time":"19",
                            "Reserved":true,
                            "User":""
                        },
                        {
                            "Time":"20",
                            "Reserved":false,
                            "User":""
                        }
                    ]
                },
                
                {
                    "TableNumber":"4",
                    "ReservationTimes":[
                        {
                            "Time":"16",
                            "Reserved":false,
                            "User":""
                        },
                        {
                            "Time":"17",
                            "Reserved":false,
                            "User":""
                        },
                        {
                            "Time":"18",
                            "Reserved":true,
                            "User":""
                        },
                        {
                            "Time":"19",
                            "Reserved":true,
                            "User":""
                        },
                        {
                            "Time":"20",
                            "Reserved":false,
                            "User":""
                        }
                    ]
                }
            ]
        },
        
        {
            "PartySize": "6",
            "Tables":[
                {
                    "TableNumber":"5",
                    "ReservationTimes":[
                        {
                            "Time":"16",
                            "Reserved":false,
                            "User":""
                        },
                        {
                            "Time":"17",
                            "Reserved":false,
                            "User":""
                        },
                        {
                            "Time":"18",
                            "Reserved":true,
                            "User":""
                        },
                        {
                            "Time":"19",
                            "Reserved":true,
                            "User":""
                        },
                        {
                            "Time":"20",
                            "Reserved":false,
                            "User":""
                        }
                    ]
                },
                
                {
                    "TableNumber":"6",
                    "ReservationTimes":[
                        {
                            "Time":"16",
                            "Reserved":false,
                            "User":""
                        },
                        {
                            "Time":"17",
                            "Reserved":false,
                            "User":""
                        },
                        {
                            "Time":"18",
                            "Reserved":true,
                            "User":""
                        },
                        {
                            "Time":"19",
                            "Reserved":true,
                            "User":""
                        },
                        {
                            "Time":"20",
                            "Reserved":false,
                            "User":""
                        }
                    ]
                }
            ]
        }
    ]
}